create_clock -period 20.000 -name sys_clk[get_ports sys_clk]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]
# clock_halt_en      ram_address_lock_en  ram_data_in_en  ram_data_out_en 
# command_reg_in_en  command_reg_out_en   a_reg_in_en     a_reg_out_en 
# b_reg_in_en        b_reg_out_en         alu_out_en      alu_sub_en 
# display_smg_in_en  pc_en                pc_load         pc_out_en 
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports clock_halt_en]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports ram_address_lock_en]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports ram_data_in_en]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports ram_data_out_en]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports command_reg_in_en]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports command_reg_out_en]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports a_reg_in_en]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports a_reg_out_en]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports b_reg_in_en]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports b_reg_out_en]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports alu_out_en]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33} [get_ports alu_sub_en]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports display_smg_in_en]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports pc_en]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports pc_load]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports pc_out_en]



set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports one_clock_input]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports clock_mode]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports always_clock]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports cpu_clock]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports cpu_clock_n]

set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports {command_counter_encode[0]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {command_counter_encode[1]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {command_counter_encode[2]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[0]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[1]}]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[2]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[3]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[4]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {command_counter_decode[5]}]

set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[1]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[2]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[3]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[4]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[5]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[6]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {cpu_bus[7]}]




set_property PULLDOWN true [get_ports {cpu_bus[0]}]
set_property PULLDOWN true [get_ports {cpu_bus[1]}]
set_property PULLDOWN true [get_ports {cpu_bus[2]}]
set_property PULLDOWN true [get_ports {cpu_bus[3]}]
set_property PULLDOWN true [get_ports {cpu_bus[4]}]
set_property PULLDOWN true [get_ports {cpu_bus[5]}]
set_property PULLDOWN true [get_ports {cpu_bus[6]}]
set_property PULLDOWN true [get_ports {cpu_bus[7]}]

set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[0]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[1]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[2]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[3]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[4]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[5]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[6]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports {a_reg_data[7]}]

set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[0]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[1]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[2]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[3]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[4]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[5]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[6]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports {b_reg_data[7]}]

set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {alu_data[0]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {alu_data[1]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {alu_data[2]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {alu_data[3]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {alu_data[4]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {alu_data[5]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {alu_data[6]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {alu_data[7]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports alu_full]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports alu_empty]

set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {pc_data[0]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports {pc_data[1]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports {pc_data[2]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports {pc_data[3]}]

set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[0]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[1]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[2]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[3]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[4]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[6]}]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports {command_reg_data[7]}]

# set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[0]}]
# set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[1]}]
# set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[2]}]
# set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[3]}]

set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[0]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[1]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[2]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports {ram_hand_address[3]}]

set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[0]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[1]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[2]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[3]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[4]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[5]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[6]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {ram_hand_data[7]}]

set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {ram_address[0]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {ram_address[1]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {ram_address[2]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {ram_address[3]}]

set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {ram_data[0]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {ram_data[1]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {ram_data[2]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {ram_data[3]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {ram_data[4]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {ram_data[5]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {ram_data[6]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {ram_data[7]}]

set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports ram_mode_select]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports ram_hand_mode]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports ram_auto_mode]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports ram_hand_write_en]

set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports {seg_sel[0]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {seg_sel[1]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {seg_sel[2]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {seg_sel[3]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {seg_led[0]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {seg_led[1]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {seg_led[2]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {seg_led[3]}]
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS33} [get_ports {seg_led[4]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports {seg_led[5]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {seg_led[6]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports {seg_led[7]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

